#!/bin/bash
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
#Download Apache Spark
wget https://www-eu.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
tar -xzf spark-2.4.4-bin-hadoop2.7.tgz

#Tidy up
rm spark-2.4.4-bin-hadoop2.7.tgz

SPARK_HOME=$HOME/spark-2.4.4-bin-hadoop2.7
